# Generated by Django 5.2 on 2025-05-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
